"""Row 2: Collision, GitLab (MR terminology, no gh-hint) plus the own-MR FYI sub-row.

Now runnable: the GitLab merge-request connector (S9b) has landed, so this row drives the REAL
GitLab collision path against a bundled mock over the ``TEAMCTX_GITLAB_API_ROOT`` seam. Two
sub-rows, exactly as spec rev 2 P1-3 requires its own evidence:

(a) an open MR on a DIFFERENT source branch touches the file the actor is about to edit, so
    work-start surfaces the collision in MR words (``Open MR !{n}``) with NO ``gh pr view`` hint
    (that hint is GitHub-only), and never reads clear.
(b) the ONLY overlapping open MR is the request branch's own MR (source_branch == the request
    branch, source_project_id == target_project_id), so the conflict check reads clear with an FYI
    naming the MR. GitLab own-detection is a distinct code path from GitHub, so it gets its own
    evidence here.

Expected blocks quote the REAL renderer output (generated by running the pipeline offline); the MR
number is the one templated span (``!{n}``), the rest is byte-exact stable copy.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

from emulation.actors import (
    DEFAULT_GITLAB_SLUG,
    SYNTHETIC_TOKEN,
    LabRepo,
    SubprocessEnv,
    build_lab_repo,
    run_cli,
)
from emulation.evidence import Expectation, RowResult, combine, passed_or_failed
from emulation.mockgl import GitLabFixtures, MockGitLab, diff_item, mr_item, pipeline_item

ROW_ID = "02"
TITLE = "Collision, GitLab"

# A green pipeline so the gate reads clean and the collision is the single subject (mirrors the
# clear-gate fixture the GitHub collision row, row 1, uses).
_CLEAR_PIPELINE = [pipeline_item(90, "success")]


def _gitlab_repo(root: Path) -> LabRepo:
    return build_lab_repo(
        root,
        slug=DEFAULT_GITLAB_SLUG,
        branch="feat/x",
        files={"src/a.py": "x\n"},
        origin_host="gitlab.com",
    )


def _collision_sub_row(tmp: Path) -> RowResult:
    repo = _gitlab_repo(tmp / "collision")
    fixtures = GitLabFixtures(
        mr_pages=[[mr_item(5, source_branch="feat/other")]],
        mr_diffs={5: [diff_item("src/a.py")]},
        pipelines=_CLEAR_PIPELINE,
    )
    with MockGitLab(fixtures) as server:
        env = SubprocessEnv(gitlab_api_root=server.api_root, gitlab_token=SYNTHETIC_TOKEN)
        run = run_cli(["work-start", "--path", "src/a.py"], cwd=repo.root, env=env)
    expectation = Expectation(
        must_match=(
            "Before you start, here is what to handle first:",
            "Open MR !{n} changed src/a.py: look at it before you edit so you don't undo "
            "each other's work",
            "Also checked: no failing checks found.",
        ),
        # never clear, no GitHub PR terminology, and no gh-hint (GitHub-only).
        must_absent=("Looks clear to start.", "gh pr view", "PR #", "Open PR"),
    )
    return passed_or_failed(ROW_ID, TITLE, run.output, expectation, note="collision")


def _own_mr_sub_row(tmp: Path) -> RowResult:
    repo = _gitlab_repo(tmp / "own")
    fixtures = GitLabFixtures(
        # own MR: same source branch as the request branch and same project id (not a fork).
        mr_pages=[[mr_item(5, source_branch="feat/x", source_project_id=1, target_project_id=1)]],
        mr_diffs={5: [diff_item("src/a.py")]},
        pipelines=_CLEAR_PIPELINE,
    )
    with MockGitLab(fixtures) as server:
        env = SubprocessEnv(gitlab_api_root=server.api_root, gitlab_token=SYNTHETIC_TOKEN)
        run = run_cli(["work-start", "--path", "src/a.py"], cwd=repo.root, env=env)
    expectation = Expectation(
        must_match=(
            "Looks clear to start.",
            "Checked: no other open MRs touch your files; no failing checks found.",
            "FYI: Your own open MR !{n} for this branch touches these files; "
            "not flagged as a collision.",
        ),
        must_absent=("Before you start", "gh pr view", "PR #"),
    )
    return passed_or_failed(ROW_ID, TITLE, run.output, expectation, note="own-MR FYI")


def run_offline() -> RowResult:
    with tempfile.TemporaryDirectory() as raw:
        tmp = Path(raw)
        parts = [_collision_sub_row(tmp), _own_mr_sub_row(tmp)]
    return combine(ROW_ID, TITLE, parts)


if __name__ == "__main__":  # pragma: no cover
    result = run_offline()
    print(result.status)
    print(result.actual)
    for outcome in result.outcomes:
        print(outcome.ok, outcome.kind, repr(outcome.subject)[:90])
