"""Row 4: Gate, GitLab (the P0 scenarios). Now runnable: the GitLab pipeline connector (S9b) has
landed, so this row drives the REAL pipeline path against a bundled mock over the
``TEAMCTX_GITLAB_API_ROOT`` seam. Four pinned sub-cases, each with no open MRs so the pipeline is
the single subject:

(a) a failed pipeline with a named failed job -> a heads-up naming that job, never clear.
(b) a CANCELED pipeline with ZERO failed jobs -> the synthetic ``pipeline canceled`` gate (there is
    no job to name, so the pipeline status carries the finding), never clear. This is the pinned
    cancel recipe: cancel before any job starts, so the pipeline is canceled but no job failed.
(c) a running pipeline -> pending wording (the gate is not confirmed green yet), never a false
    green.
(d) ZERO pipelines for the ref -> the disabled "no pipeline ran" note, never clear. This is the
    other half of the GitHub/GitLab asymmetry: GitHub's zero-check-runs reads CLEAR (row 3d), but
    GitLab's zero-pipelines is honestly unverified, because a GitLab project can simply have no CI
    configured for the ref. The gate-clear phrase ("no failing checks found") must NOT appear.

Expected blocks quote the REAL renderer output (generated by running the pipeline offline), all
byte-exact stable copy.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

from emulation.actors import (
    DEFAULT_GITLAB_SLUG,
    SYNTHETIC_TOKEN,
    LabRepo,
    SubprocessEnv,
    build_lab_repo,
    run_cli,
)
from emulation.evidence import Expectation, RowResult, combine, passed_or_failed
from emulation.mockgl import GitLabFixtures, MockGitLab, job_item, pipeline_item

ROW_ID = "04"
TITLE = "Gate, GitLab"

_NO_MRS: list[list[dict[str, object]]] = [[]]  # no open MRs: the pipeline is the single subject


def _gitlab_repo(root: Path) -> LabRepo:
    return build_lab_repo(
        root,
        slug=DEFAULT_GITLAB_SLUG,
        branch="feat/x",
        files={"src/a.py": "x\n"},
        origin_host="gitlab.com",
    )


def _run(tmp: Path, name: str, fixtures: GitLabFixtures) -> str:
    repo = _gitlab_repo(tmp / name)
    with MockGitLab(fixtures) as server:
        env = SubprocessEnv(gitlab_api_root=server.api_root, gitlab_token=SYNTHETIC_TOKEN)
        run = run_cli(["work-start", "--path", "src/a.py"], cwd=repo.root, env=env)
    return run.output


def _failed_job_sub_row(tmp: Path) -> RowResult:
    fixtures = GitLabFixtures(
        mr_pages=_NO_MRS,
        pipelines=[pipeline_item(91, "failed")],
        pipeline_jobs={91: [job_item("test", "failed"), job_item("build", "success")]},
    )
    output = _run(tmp, "failed", fixtures)
    expectation = Expectation(
        must_match=(
            "Before you start, here is what to handle first:",
            "Check 'test' is failing on this branch: fix it or wait for a green build "
            "before relying on it",
        ),
        must_absent=("Looks clear to start.",),
    )
    return passed_or_failed(ROW_ID, TITLE, output, expectation, note="failed pipeline + named job")


def _canceled_sub_row(tmp: Path) -> RowResult:
    fixtures = GitLabFixtures(
        mr_pages=_NO_MRS,
        pipelines=[pipeline_item(92, "canceled")],
        pipeline_jobs={92: []},  # canceled before any job started: zero failed jobs
    )
    output = _run(tmp, "canceled", fixtures)
    expectation = Expectation(
        must_match=(
            "Before you start, here is what to handle first:",
            "Check 'pipeline canceled' is failing on this branch: fix it or wait for a green "
            "build before relying on it",
        ),
        must_absent=("Looks clear to start.",),
    )
    return passed_or_failed(ROW_ID, TITLE, output, expectation, note="canceled pipeline (0 jobs)")


def _running_sub_row(tmp: Path) -> RowResult:
    fixtures = GitLabFixtures(mr_pages=_NO_MRS, pipelines=[pipeline_item(93, "running")])
    output = _run(tmp, "running", fixtures)
    expectation = Expectation(
        must_match=(
            "Heads up: I can't confirm the important things yet:",
            "Failing checks: CI checks are still running, so the gate isn't confirmed "
            "green yet. Wait for the build or check the run before relying on a green gate.",
        ),
        must_absent=("Looks clear to start.", "no failing checks found"),
    )
    return passed_or_failed(ROW_ID, TITLE, output, expectation, note="running pipeline (pending)")


def _zero_pipelines_sub_row(tmp: Path) -> RowResult:
    fixtures = GitLabFixtures(mr_pages=_NO_MRS, pipelines=[])  # no pipeline ran for this ref
    output = _run(tmp, "zero", fixtures)
    expectation = Expectation(
        must_match=(
            "no pipeline ran for this branch, so the gate is unverified",
        ),
        # the asymmetry: unlike GitHub's zero-check-runs (row 3d), the GitLab gate never reads
        # clear here, so the gate-clear phrase must be absent.
        must_absent=("no failing checks found",),
    )
    return passed_or_failed(
        ROW_ID, TITLE, output, expectation, note="zero pipelines (disabled note)"
    )


def run_offline() -> RowResult:
    with tempfile.TemporaryDirectory() as raw:
        tmp = Path(raw)
        parts = [
            _failed_job_sub_row(tmp),
            _canceled_sub_row(tmp),
            _running_sub_row(tmp),
            _zero_pipelines_sub_row(tmp),
        ]
    return combine(ROW_ID, TITLE, parts)


if __name__ == "__main__":  # pragma: no cover
    result = run_offline()
    print(result.status)
    print(result.actual)
    for outcome in result.outcomes:
        print(outcome.ok, outcome.kind, repr(outcome.subject)[:90])
